#!/bin/bash

echo "Bash Script to Create DIPOA APPLICATION"
echo "Author: Alireza Olama"

options="-O3 -m64 -std=c++11"
#cplex_path="/home/alireza/cplex/cplex/include"
#consert_path="/home/alireza/cplex/concert/include"

#cplex_lib="/home/alireza/cplex/cplex/lib/x86-64_linux/static_pic"
#consert_lib="/home/alireza/cplex/concert/lib/x86-64_linux/static_pic"

gurobi_path="/home/alireza/gurobi903/linux64/include"
gurobi_lib="/home/alireza/gurobi903/linux64/lib"

echo "Do you want to compile the application? (yes/no)"

read ans

if [ $ans == "yes" ]
then
    echo "Application is compiling..."
    mpic++ $options -I$gurobi_path -L$gurobi_lib includes/*.h src/*.cpp test_functions/*.h utils/*.cpp  main.cpp -lgurobi_g++5.2 -lgurobi_c++ -lgurobi90   -o dipoa
    echo "done!"
    echo "Do you want to run the application? (yes/no)"
   
    read ans

	if [ $ans == "yes" ]
	then
    	echo "How many cores you want to use? "
    	read ncores
    	echo "Application is running..." 
    	mpirun --hostfile hostfile -n $ncores ./dipoa
    	echo "end"
	fi	
else
    

 ans=yes

if [ $ans == "yes" ]
then
    echo "How many cores you want to use? "
    read ncores
    echo "Application is running..." 
    mpirun --hostfile hostfile -n $ncores ./dipoa
    echo "end" 
fi


fi

