#!/bin/bash

echo "Bash Script to Create DIPOA APPLICATION"
echo "Author: Alireza Olama"

options="-DIL_STD -O3 -w"
cplex_path="/home/alireza/cplex/cplex/include"
consert_path="/home/alireza/cplex/concert/include"

cplex_lib="/home/alireza/cplex/cplex/lib/x86-64_linux/static_pic"
consert_lib="/home/alireza/cplex/concert/lib/x86-64_linux/static_pic"

echo "Do you want to compile the application? (yes/no)"

read ans

if [ $ans == "yes" ]
then
    echo "Application is compiling..."
    mpic++ $options  -I$cplex_path -I$consert_path -L$cplex_lib -L$consert_lib includes/*.h src/*.cpp test_functions/*.h utils/*.cpp  main.cpp -lilocplex -lconcert -lcplex -lm -lpthread -ldl -o dipoa
    echo "done!"
    echo "Do you want to run the application? (yes/no)"
   
    read ans

	if [ $ans == "yes" ]
	then
    	echo "How many cores you want to use? "
    	read ncores
    	echo "Application is running..." 
    	mpirun --hostfile hostfile -n $ncores ./dipoa
    	echo "end"
	fi	
else
    echo "Do you want to run the application? (yes/no)"

read ans

if [ $ans == "yes" ]
then
    echo "How many cores you want to use? "
    read ncores
    echo "Application is running..." 
    mpirun --hostfile hostfile -n $ncores ./dipoa
    echo "end" 
fi


fi

